# Generated by Django 5.2 on 2026-04-28 12:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500)),
                ('video_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('videos_imported', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('videos_updated', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('api_units_used', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial')], default='success', max_length=20)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-synced_at',),
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500)),
                ('published_at', models.DateTimeField()),
                ('duration_seconds', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('view_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('like_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('category', models.CharField(choices=[('aqeedah', 'عقيدة - Islamic Creed'), ('fiqh', 'فقه - Islamic Jurisprudence'), ('quran', 'قرآن وتفسير - Quran & Tafsir'), ('seerah', 'سيرة نبوية - Prophetic Biography'), ('hadith', 'حديث - Hadith Sciences'), ('akhlaq', 'أخلاق وتزكية - Ethics & Purification'), ('dawah', "دعوة - Da'wah & Outreach"), ('fatawa', 'فتاوى - Islamic Rulings'), ('ramadan', 'رمضان - Ramadan Special'), ('other', 'أخرى - Other')], default='other', max_length=50)),
                ('difficulty', models.CharField(choices=[('beginner', 'مبتدئ - Beginner'), ('intermediate', 'متوسط - Intermediate'), ('advanced', 'متقدم - Advanced'), ('general', 'عام - General Audience')], default='general', max_length=20)),
                ('ai_summary', models.TextField(blank=True)),
                ('seo_description', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, max_length=300)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-published_at',),
                'indexes': [models.Index(fields=['video_id'], name='videos_vide_video_i_595dd6_idx'), models.Index(fields=['category'], name='videos_vide_categor_c4366b_idx'), models.Index(fields=['difficulty'], name='videos_vide_difficu_b00c59_idx'), models.Index(fields=['published_at'], name='videos_vide_publish_dd5f2e_idx'), models.Index(fields=['is_featured'], name='videos_vide_is_feat_70e3c9_idx'), models.Index(fields=['is_active'], name='videos_vide_is_acti_dd8033_idx')],
            },
        ),
        migrations.CreateModel(
            name='VideoPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_links', to='videos.playlist')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_links', to='videos.video')),
            ],
            options={
                'ordering': ('playlist', 'position'),
                'unique_together': {('video', 'playlist')},
            },
        ),
    ]
