# Generated by Django 5.2 on 2026-04-28 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='videos.video')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user'], name='videos_favo_user_id_cbd741_idx'), models.Index(fields=['video'], name='videos_favo_video_i_14f04d_idx')],
                'unique_together': {('user', 'video')},
            },
        ),
    ]
