# Generated by Django 5.2 on 2026-04-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_emailverificationpending'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='youtube_category_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='video',
            name='youtube_category_title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['youtube_category_id'], name='videos_vide_youtube_927108_idx'),
        ),
    ]
