# Generated by Django 5.2 on 2026-04-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_spiritpin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('user', 'مستخدم'), ('moderator', 'مشرف'), ('admin', 'أدمن')], default='user', max_length=20),
        ),
    ]
