# Generated by Django 5.2 on 2026-04-28 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_alter_userprofile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MosqueLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mosque_name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('lesson_time', models.TimeField(blank=True, null=True)),
                ('manual_time_text', models.CharField(blank=True, max_length=120)),
                ('is_weekly', models.BooleanField(default=True)),
                ('weekday', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'الاثنين'), (1, 'الثلاثاء'), (2, 'الأربعاء'), (3, 'الخميس'), (4, 'الجمعة'), (5, 'السبت'), (6, 'الأحد')], null=True)),
                ('one_time_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mosque_lessons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('is_weekly', 'weekday', 'one_time_date', 'lesson_time', '-created_at'),
                'indexes': [models.Index(fields=['is_weekly'], name='videos_mosq_is_week_fb83ee_idx'), models.Index(fields=['weekday'], name='videos_mosq_weekday_98ef4b_idx'), models.Index(fields=['one_time_date'], name='videos_mosq_one_tim_9594e4_idx'), models.Index(fields=['is_active'], name='videos_mosq_is_acti_67971d_idx')],
            },
        ),
    ]
