# Generated by Django 5.2 on 2026-04-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('preferred_category', models.CharField(blank=True, choices=[('aqeedah', 'عقيدة - Islamic Creed'), ('fiqh', 'فقه - Islamic Jurisprudence'), ('quran', 'قرآن وتفسير - Quran & Tafsir'), ('seerah', 'سيرة نبوية - Prophetic Biography'), ('hadith', 'حديث - Hadith Sciences'), ('akhlaq', 'أخلاق وتزكية - Ethics & Purification'), ('dawah', "دعوة - Da'wah & Outreach"), ('fatawa', 'فتاوى - Islamic Rulings'), ('ramadan', 'رمضان - Ramadan Special'), ('other', 'أخرى - Other')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-joined_at',),
                'indexes': [models.Index(fields=['chat_id'], name='bot_telegra_chat_id_b7c810_idx'), models.Index(fields=['is_active'], name='bot_telegra_is_acti_3192cc_idx'), models.Index(fields=['preferred_category'], name='bot_telegra_preferr_e5af05_idx')],
            },
        ),
    ]
